---
variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  SAST_EXCLUDED_ANALYZERS: "eslint,nodejs-scan,gosec"

include:
  - project: templates/ci
    file: DockerInDockerTemplate.yml
  - template: Security/SAST.gitlab-ci.yml

stages:
  - verify
  - test
  - build
  - release
  - notify

sonarqube-backend:
  stage: verify
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - cd backend
    - >
      sonar-scanner 
      -Dsonar.projectKey=${SONAR_PROJECT_KEY_BACKEND}
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.sources=.
      -Dsonar.login=${SONAR_LOGIN_BACKEND}
      -Dsonar.projectName=ALEXANDERVOZNYY_MOMO_STORE_BACKEND

test-backend:
  stage: test
  image: golang:1.20
  script:
    - cd backend
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)
    - go test -v ./...

build-backend:
  stage: build
  image: docker:20.10.12-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd backend
    - >
      docker build  --tag $CI_REGISTRY_IMAGE/momostore-backend:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE/momostore-backend:$CI_COMMIT_SHA

upload-latest:
  variables:
    GIT_STRATEGY: none
  stage: release
  image: docker:20.10.12-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/momostore-backend:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/momostore-backend:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/momostore-backend:latest
    - docker push $CI_REGISTRY_IMAGE/momostore-backend:latest
  needs:
    - build-backend


telegram-notification:
  stage: notify
  when: manual
  script:
    - 'curl -X POST -H "Content-type: application/json" --data "{\"chat_id\": \"-1001634310929\", \"text\": \"Вышла новая версия momostore-backend пельменной — ${VERSION}. Скачать momostore-backend можно по команде docker pull — ${CI_REGISTRY_IMAGE}/momostore-backend:latest\"}" "https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage"'
  needs:
    - job: upload-latest
