---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-basic-auth
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "yc-clusterissuer"
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - admin'
spec:
  tls:
    -  hosts:
       - "{{ .Values.alertmanager }}"
       secretName: "alert-domain-name-secret"

    -  hosts:
       - "{{ .Values.prometheus }}"
       secretName: "prom-domain-name-secret"

  rules:
  - host: {{ .Values.alertmanager }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-monitoring-kube-prometh-alertmanager
            port:
              number: 9093

  - host: {{ .Values.prometheus }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-monitoring-kube-prometh-prometheus
            port:
              number: 9090
